// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhthFHPAvcP02OgT7TGB_91zAe0l4V4c',
    appId: '1:243347299804:web:f1b2fc72cde6d6d5ac0319',
    messagingSenderId: '243347299804',
    projectId: 'houseoftailors1-786c5',
    authDomain: 'houseoftailors1-786c5.firebaseapp.com',
    storageBucket: 'houseoftailors1-786c5.firebasestorage.app',
    measurementId: 'G-YQGN2LMG0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6-bdYmMxc0GFMUCA-CreCnCN603PBGM',
    appId: '1:243347299804:android:eb16198412a9aa9bac0319',
    messagingSenderId: '243347299804',
    projectId: 'houseoftailors1-786c5',
    storageBucket: 'houseoftailors1-786c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpQpYukanl6DIOABcAqzMbJqjmfuKFFE',
    appId: '1:243347299804:ios:b3606cab79861c70ac0319',
    messagingSenderId: '243347299804',
    projectId: 'houseoftailors1-786c5',
    storageBucket: 'houseoftailors1-786c5.firebasestorage.app',
    iosBundleId: 'com.example.houseoftailors',
  );

}